
# Project ID
project_id = "wshetxovyxtfqohhbvpg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

# Schedule for queue workers
[functions.artistDiscovery]
verify_jwt = false

[functions.albumDiscovery]
verify_jwt = false

[functions.trackDiscovery]
verify_jwt = false

[functions.producerIdentification]
verify_jwt = false

[functions.socialEnrichment]
verify_jwt = false

[functions.readQueue]
verify_jwt = false

[functions.sendToQueue]
verify_jwt = false

[functions.deleteFromQueue]
verify_jwt = false

[functions.startDiscovery]
verify_jwt = false

[functions.manageQueue]
verify_jwt = false

[functions.queueMonitor]
verify_jwt = false
