
project_id = "wshetxovyxtfqohhbvpg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enabled = true

[auth.sms]
enabled = true

[auth.external.github]
enabled = true
client_id = "env(SUPABASE_AUTH_GITHUB_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GITHUB_SECRET)"
url = "env(SUPABASE_AUTH_GITHUB_URL)"

[analytics]
enabled = false
port = 54327

[experimental]
trace = false

# Configure Edge Functions
[functions]
  [functions.artistDiscovery]
    verify_jwt = false
  
  [functions.albumDiscovery]
    verify_jwt = false
  
  [functions.trackDiscovery]
    verify_jwt = false
  
  [functions.producerIdentification]
    verify_jwt = false
    
  [functions.socialEnrichment]
    verify_jwt = false
    
  [functions.cronQueueProcessor]
    verify_jwt = false
    
  [functions.pipelineMonitor]
    verify_jwt = false
